### ISSUE TITLE
Doesn't support R6

### ISSUE THREAD

**Issue by LoganDark** [easy-games/chickynoid#2]
I understand that Roblox is heavily pushing in the direction of R15, but in a lot of cases it's just not acceptable. Especially when players choose that they want to have an R6 avatar, but are forced into R15 instead. The demo place currently forces you into R15 and I heard that this character controller is not yet compatible with R6. This is a major blocker towards me using this in any of my games and I'm sure many others feel the same way, so I'm opening this issue to track R6 support.

**Comment by MrChickenRocket** [comment]
You can use a R6 rig if you like. See: charactermods
