### ISSUE TITLE
Player's Character Model doesn't face direction that Player is looking in.

### ISSUE THREAD

**Issue by tqoac** [easy-games/chickynoid#32]
It's just a small issue I noticed; I genuinely don't know if this can only be fixed by forking the CameraModule.

When in first person, your character model will face the direction your facing, however, scrolling out of first person, and your character will default to the direction you were previously walking in. Furthermore, when in first person and your looking around, other players can't see you facing the direction your actually facing in.

**Comment by TheGibusGuy** [comment]
You can force the character model to where you're looking by setting aimLock to 1.

`local module = {}
local Chickynoid = game:GetService("ReplicatedFirst").Packages.Chickynoid
local Enums = require(Chickynoid.Enums)

function module:Setup(simulation)
	
	simulation.constants.maxSpeed = 32
	simulation.constants.airSpeed = 4
	simulation.constants.accel = 8
	simulation.constants.airAccel = 80
	simulation.constants.jumpPunch = 25
	simulation.constants.turnSpeedFrac = 10
	simulation.constants.runFriction = 0
	simulation.constants.brakeFriction = 0.15
	simulation.constants.maxGroundSlope = 0.7
	simulation.constants.jumpThrustPower = 0
	simulation.constants.jumpThrustDecay = 0
	simulation.constants.gravity = -70
	simulation.constants.crashLandBehavior = Enums.Crashland.FULL_BHOP
	simulation.constants.aimlock = 1 -- the part you're looking for
	
	local MoveTypeTRWalking = require(script.Parent.utils.MoveTypeTRWalking)
	MoveTypeTRWalking:ModifySimulation(simulation)
	
	simulation:SetMoveState("TRWalking")
end

function module:GetCharacterModel(userId)
	--return game.ReplicatedFirst.Packages.Chickynoid.Assets.BigHeadRig
	return nil
end 


return module`
