### ISSUE TITLE
chickynoid.rbxl in GitHub protentially doesn't match version in game?

### ISSUE THREAD

**Issue by NNickey** [easy-games/chickynoid#4]
Current version of [chickynoid.rbxl](https://github.com/easy-games/chickynoid/blob/main/chickynoid.rbxl)
has weird collision issues. 

Floating about 2 studs from the ground, and once you jump, you seem to float all the way up to around 130.

Attempting to disable Terrain Collisions didn't resolve this issue.

**Comment by MrChickenRocket** [comment]
Should be resolved now. Sorry was still working on terrain collision!
