### ISSUE TITLE
Spam Jumping with chickynoid force GetStandingPart to return nil

### ISSUE THREAD

**Issue by Aztup** [easy-games/chickynoid#9]
If you spam jump with chickynoid the GetStandingPart function is returning nil causing the kill bricks to not work if you spam jump over it.

It seem that the issue is coming from this part of the code

![image](https://user-images.githubusercontent.com/55710232/172908919-372522df-22eb-4a2a-bc0f-98f42e185dfc.png)

**Comment by MrChickenRocket** [comment]
Will look into it!

**Comment by MrChickenRocket** [comment]
Sorted.
